//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaghavFirstAngular
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountRequirement()
        {
            this.DiscountRequirement1 = new HashSet<DiscountRequirement>();
        }
    
        public int Id { get; set; }
        public int DiscountId { get; set; }
        public string DiscountRequirementRuleSystemName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> InteractionTypeId { get; set; }
        public bool IsGroup { get; set; }
    
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountRequirement> DiscountRequirement1 { get; set; }
        public virtual DiscountRequirement DiscountRequirement2 { get; set; }
    }
}
